import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#ab1f82",
        "on-secondary-fixed-variant": "#594400",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb4a4",
        "on-tertiary-fixed": "#3d0600",
        background: "#f9f9f9",
        "primary-container": "#ff69c9",
        "on-secondary-container": "#6e5400",
        "on-secondary": "#ffffff",
        tertiary: "#b72301",
        error: "#ba1a1a",
        "on-background": "#1b1b1b",
        "surface-dim": "#dadada",
        "surface-container-high": "#e8e8e8",
        "surface-bright": "#f9f9f9",
        outline: "#88717c",
        "primary-fixed-dim": "#ffaeda",
        "inverse-primary": "#ffaeda",
        "secondary-fixed-dim": "#f4bf00",
        "on-tertiary-fixed-variant": "#8c1800",
        "on-primary-container": "#6e0051",
        "secondary-container": "#fec700",
        surface: "#f9f9f9",
        "tertiary-container": "#ff795b",
        "surface-container-low": "#f3f3f3",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f1f1f1",
        "surface-container": "#eeeeee",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "outline-variant": "#dbbfcb",
        "tertiary-fixed": "#ffdad3",
        "on-tertiary-container": "#711200",
        "primary-fixed": "#ffd8ea",
        "surface-variant": "#e2e2e2",
        secondary: "#755b00",
        "on-surface": "#1b1b1b",
        "surface-container-highest": "#e2e2e2",
        "on-primary-fixed": "#3c002b",
        "surface-tint": "#ab1f82",
        "secondary-fixed": "#ffdf92",
        "on-primary-fixed-variant": "#890066",
        "inverse-surface": "#303030",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#55414b",
        "on-secondary-fixed": "#241a00",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Work Sans", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      boxShadow: {
        brutalist: "6px 6px 0px 0px rgba(0,0,0,1)",
        "brutalist-sm": "4px 4px 0px 0px rgba(0,0,0,1)",
        "brutalist-lg": "8px 8px 0px 0px rgba(0,0,0,1)",
        "brutalist-xl": "12px 12px 0px 0px rgba(0,0,0,1)",
        "brutalist-yellow": "8px 8px 0px 0px rgba(254,199,0,1)",
        "brutalist-pink": "8px 8px 0px 0px rgba(255,105,201,1)",
        "brutalist-white": "4px 4px 0px 0px rgba(255,255,255,1)",
      },
    },
  },
  plugins: [],
};

export default config;